### PR TITLE
Added button to Delete User

### LINKED ISSUE #62: As a user, I want to be able to delete my profile, so I can stop using the service

### PR DESCRIPTION
**Pull request by migurski**
- [x] A user can delete their profile
- [x] Do we need a confirmation screen for this?

Closes #62.

### CODE REVIEW

**Comment by migurski** [comment]
@phae, assigning you so you can make a judgement call about how to handle deletion confirmation.

**Comment by phae** [comment]
Yes, or at least an alert to say "Really?".  Luckily, signing back up wouldn't be particularly difficult.

**Comment by migurski** [comment]
Due to the S3 I think I can't upload a screenshot of the Travis test failure due to S3.

**Comment by migurski** [comment]
I added a confirmation for the delete button.

**Pull request merged**
