### PR TITLE
Notify users of fires

### LINKED ISSUE #41: As an admin of the service, I want to send emergency notifications so people know when they are in danger
Acceptance Criteria:

1. An admin user must be able to log into an administrative area
2. The admin user must be able to view emergency data on a map to identify affected areas see #60 
3. The admin user can create an emergency notification that will be sent to all users 
4. The emergency notification must fit within the SMS limit of 140 characters

Notes:
For the purposes of the MVP for the prototype, these notifications go to all users. The prototype description does not require that admins publish notifications to specific geographical areas.

Relevant prototype description:

> In addition, the working prototype will provide the authorized administrative users with the ability to publish notifications and track, and analyze and visualize related data. The working prototype does not need to implement any authentication or authorization against an external directory or authentication mechanism.
--------

Template: https://github.com/VeryLittleGravitas/CDTADPQ/blob/master/CDTADPQ/web/templates/send-alert.html

### PR DESCRIPTION
**Pull request by migurski**
Closes #41.

- [x] Admin user can log into an admin area
- [x] Current fires are shown in a list
- [x] Admin user can choose one to tell people about
- [x] Admin user can write a short message
- [x] Messages probably go out?
- [x] Show how many characters the message uses
- [x] Send to users within some reasonable distance of the event (https://github.com/VeryLittleGravitas/CDTADPQ/issues/74)

### CODE REVIEW

**Comment by migurski** [comment]
Reassigning this to you, @phae. You can try sending an alert from http://vlg-ctdadpq-pr-78.herokuapp.com/admin/send-alert/fire/2017-OKECU-170107, which should reach you if you are registered. Username/password for the admin is admin/verylittlegravitas. This page needs content help: http://vlg-ctdadpq-pr-78.herokuapp.com/admin/sent

**Comment by phae** [comment]
http://vlg-ctdadpq-pr-78.herokuapp.com/admin/send-alert/fire/2017-OKECU-170107 took ages to load something and then that something was "application error".

**Comment by migurski** [comment]
These are the words that need an update:

> Admin - Current emergencies
> 
> You just sent an alert to one bajillion people!
> 
> Some stats about who it was sent to etc. see more

Follow-up in https://github.com/VeryLittleGravitas/CDTADPQ/issues/82.

**Comment by phae** [comment]
OK LGTM, with new issue for sent page.

**Pull request merged**
